config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  before_action :set_bookmark, only: %i[destroy]

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(strong_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def strong_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container d-flex flex-column align-item-center">
  <h1>New bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Create Bookmark", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="header navbar navbar-expand-lg bg-body-tertiary d-flex flex-row justify-content-between px-5 align-items-center">
    <div><img src="https://www.slashfilm.com/img/slashfilm-logo.svg" style="width: 120px;"></div>
    <ol class="d-flex flex-row gap-2 list-unstyled m-0">
      <li class="login">Login</li>
    </ol>
  </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="w-100% banner d-flex flex-column justify-content-center align-items-center">
 <h1>Save any kind of movies</h1>
</div>
<div class="d-flex flex-column justify-content-center align-items-center mt-5">
  <div class="list-button">
    <h3>All Lists</h3>
    <%= link_to "create new list",  new_list_path, class: "btn btn-success text-light rounded-pill" %>
  </div>
  <div class="d-flex flex-row p-5 flex-wrap justify-content-center align-items-center gap-2 w-75">
    <ul class="d-flex flex-row justify-content-center align-items-center gap-4 list-unstyled flex-wrap">
    <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list), class:"card" %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/lists/new.html.erb
<div class="d-flex flex-column justify-content-center align-items-center mt-5">
  <h1 class="h1 mb-3">Create a List</h1>
  <%= form_with model: @list do |f| %>
    <div class="form">
      <%= f.text_field :name, placeholder: "list name" %>
      <%= f.submit class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="d-flex flex-column justify-content-center align-items-center mt-5">
  <h1 id="name"><strong><%= @list.name %></strong></h1>
  <br>
  <ul class="list-group">
    <% @list.bookmarks.each do |bookmark| %>
      <div id="list"><li class="list-group-item d-flex flex-row justify-content-between align-items-center"><%= bookmark.comment %>-----<%= bookmark.movie.title %><%= link_to "Delete",
    bookmark_path(bookmark),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-danger ms-2"
  %></li></div>
    <% end %>
  </ul>
  <br>
  <%= link_to "Add a new bookmark", new_list_bookmark_path(@list), class:"btn btn-primary" %>
  <br>
  <%= link_to "Return to lists", lists_path, class:"btn btn-primary" %>
</div>